if IsDLCEnabled(REIGN_OF_GIANTS) or IsDLCEnabled(CAPY_DLC) then 

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.FLOUR = {
	"Loose non-food",
}
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BREAD = {
	"Still not meat",
}

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CHEESE = {
	"What's that smell ... it can not be edible",
}

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BANANAPIE = {
	"Still not meat",
}

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SHELLDUST = {
	"Loose non-food",
}

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.MUSHROOMSOUP = {
	"Disgusting mash",
}

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.NUTS = {
	"Sour fruit...non edible",
}

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.NUTS_COOKED = {
	"Still non edible",
}

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.NUTMUFFIN = {
	"Still not meat",
}

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SALT = {
	"Loose and salt",
}

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.OVERSALT = {
	"Disgusting mash",
}

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TRUFFLES_PLANTED = {
	"Stinky mushroom",
}

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TRUFFLES = {
	"Stinky mushroom",
}

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TRANSTRUFFLES = {
	"Pickled berries with just a touch of spice",
}

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TRUFFLEHAM = {
	"Meat with a intensive smell",
}

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TRUFFLEEGS = {
	"Delicious eggs!",
}

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.RIBS = {
	"This is a real meal for a warrior",
}

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.PANCAKES = {
	"Sweet...but I don't want eat this",
}

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.LEMON_COCKTAIL = {
	"Still not meat",
}

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.MINHIBITOR = {
	"This destroys fear!",
}

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.MOSQUITO_MILK = {
	"Strange milk...",
}

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CACTUS_COCKTAIL = {	
	"Still not meat",
}

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.FERNSPINACH = {	
	"Still not meat",
}
end